### ISSUE TITLE
You need the option for fopen correct for accessing binary data, "w" to "wb"

### ISSUE THREAD

**Issue by digiponta** [Ricardicus/mjpeg-avi#2]
You need the option for the fopen correct for accessing binary data, "w" to "wb" with Visual Studio.

For example:
correct:	errno_t ret = fopen_s( &fp, "Video.avi", "wb"); // for accessing binary data
original:   FILE * fp = fopen("Video.avi", "w");

If not so, fputc will add 0xd for 0x0a or 0x0D for 0x0a, automatically. The your code can't work right for it.

Thank you in advance.
digip

**Comment by Ricardicus** [comment]
Thanks!

I had a POSIX compliant bias.. fixed now :)
