### ISSUE TITLE
Please add license

### ISSUE THREAD

**Issue by mixern6** [Ricardicus/mjpeg-avi#3]
Please add license description file.
Thanks!

**Comment by Ricardicus** [comment]
License added. Have you found this software useful somewhere?

**Comment by mixern6** [comment]
I have a small project for projecting videos on 3D models and need to convert proprietary video formats to something readable by Qt multimedia. The generated files don't pass validation in riffpad, can't be opened in Avidemux and QMediaPlayer. It seems, there is something wrong about chunk sizes, at least riffpad shows incorrect numbers. However, the files can be opened and played in MPC

**Comment by Ricardicus** [comment]
Ok, interesting. I built this thing many years ago, but I can perhaps take a look at it and fix it if I find where it is wrong. Thanks!

**Comment by Ricardicus** [comment]
I found a bug and think I fixed the program now. Can you try it out now?

**Comment by mixern6** [comment]
I see a few problems:
After this line fwriteDWORD(file_ptr, strh.dwSampleSize);
There should be rcFarme https://manualzz.com/doc/21076623/avi-file-format-1 :
    RECT rcFarme;
    rcFarme.left = 0;
    fwriteDWORD(file_ptr, rcFarme.left);
    rcFarme.top = 0;
    fwriteDWORD(file_ptr, rcFarme.top);
    rcFarme.right = 800; //width
    fwriteDWORD(file_ptr, rcFarme.right);
    rcFarme.bottom = 600; //height
    fwriteDWORD(file_ptr, rcFarme.bottom);

riffpad expects it, but it is not there and junk information is displayed instead.
Also to make it work for windows, all "r" have to be replaced with "rb" otherwise it doesn't read the jpg files.
I fixed these on my side, but the output files are still not valid.

**Comment by Ricardicus** [comment]
my riffpad did not complain, and QuickTime now works after the fix on my mac machine. I will fix the "rb".

Sorry I don't find the "rcFrame" in that doc.

**Comment by Ricardicus** [comment]
Thank you so much! I fixed it over here now also.

**Comment by Ricardicus** [comment]
Does it look good on your side now also?
